### ISSUE TITLE
NavigationAdvancedSample back handle

### ISSUE THREAD

**Issue by TepesLucian** [android/architecture-components-samples#1005]
I'm not sure if this is an issue or not but `NavigationAdvancedSample` back handling seems off. If I open the about fragment in the first tab switch to second tab and tap on a user going back isn't the reverse flow. It goes back to user list -> welcome screen (no about screen in the first tab) -> exit the app. If you don't exit the app in that case and tap the home tab again (even though it's reselected) then you will see the about screen.

**Comment by nhatpv-1627** [comment]
I don't know that is a feature or a bug =))

**Comment by Skyyo** [comment]
Definitely not an expected behaviour for most users. 
Back pressing from `leaderbord tab` should take you to the top destination of the `home tab`.
Currently it does exactly that only if you tap on `home tab`. But back pressing from `leaderbord tab` will result in a root destination being shown on the `home tab`.

@ianhanniballake can you please give us any insight on whether this will be fixed in future updates, or should we implement workarounds?

**Comment by ianhanniballake** [comment]
See #997
