### ISSUE TITLE
question about AutoClearedValue

### ISSUE THREAD

**Issue by DJafari** [android/architecture-components-samples#158]
in all documents and articles says **don't need to set null for class field of activity or fragment when destroyed** because `GC` cleared them automatically for release memory, but this examples google use a simple helper ([AutoClearedValue](https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/util/AutoClearedValue.java)) for release memory of DataBinding and adapter fields for fragment, i want to know it is necessary ?

**Comment by JakeWoki** [comment]
I want to know too

**Comment by DJafari** [comment]
@JakeWoki it is only exist in github example

**Comment by goransipic** [comment]
@DJafari @JakeWoki  Look at this workflow, you have Activity and Fragment A and then you add another Fragment B with replace using addToBackStack() metod when you are doing transaction to replace Fragment A. For Fragment A method onFragmentViewDestroyed will be called because it's not visible anymore but it will not be destroyed.

**Comment by amrro** [comment]
Thanks, @goransipic 
I wondered for a while why!
