### ISSUE TITLE
LiveData should make old data observable

### ISSUE THREAD

**Issue by ivotai** [android/architecture-components-samples#216]
`public interface Observer<T> {`
`      void onChanged(@Nullable T newValue,@Null T oldValue);`
`}`
Adapter stands for view, holding old data is not view's duty, is it?

**Comment by arifnadeem7** [comment]
I know, right? The whole point of using an architecture is to separate concerns, these examples do not do justice to otherwise brilliantly conceived architecture components.

This code is all over the place right now, Views have business logic while ViewModels are doing nothing, the way LiveData is demonstrated doesn't have any practical use case, I mean how often does the user name change? Even if it does, there's no way right now to demonstrate or see this change.

I really hope that they change this soon since these example are likely to be considered as bibles for writing Android apps, I am afraid that people who are new to Android will assume that this is the correct way to write apps.

**Comment by ianhanniballake** [comment]
Please file feature requests against Lifecycle (and hence, LiveData) on [the issue tracker](https://issuetracker.google.com/issues/new?component=413132) if you're still interested in this feature request.
