### ISSUE TITLE
How to use Room database across Instant App feature modules?

### ISSUE THREAD

**Issue by Karthi-R** [android/architecture-components-samples#274]
Actually I'm preparing for Instant App. Consider I've the following feature modules. And each module has its own data layer with Entity and Dao classes.

 ->feature-base
 ->feature-profile
 ->feature-payment
 ->feature-dashboard

Where should I place my "RoomDatabase" class?

I want to keep all my app data in single database. I can't place my "RoomDatabase" it in base module or at each feature!

Kindly suggest the right way of using "Room Database" in Instant App feature modules.

**Comment by karntrehan** [comment]
Ran into exactly this issue yesterday. The base module is where I have my RoomDatabase class, but it requires access to my entities sitting in the feature modules. 

Do we add all the entities into the base? 
When the user download the instant app, the base will create the entire db with all the entities?

**Comment by Shakezulla57** [comment]
I'm looking for some insight into this as well.

**Comment by sampengilly** [comment]
I feel like there are three possible solutions here and each probably has their own pros and cons. Interest to hear what others come up with too.

Option 1 (Database per feature module):
Each feature module has a database and data layer that it exclusive to that module. The Database, DAOs, Entities, etc. are all contained within the feature module. The obviously results in a cleaner separation of modules, and integrity of data between instant apps and the full app (as there is no change in data architecture). On the other hand it may affect performance and it definitely affects the way relationships can be formed and prevents data relationships being formed between modules.

Option 2 (Database per app module):
Each feature module defines its own DAOs and Entities, but databases are defined by the various app modules (e.g. 1 for installed, 1 for Feature A instant, 1 for Feature B instant, etc...). Each of these app module databases defines only the DAOs required for that version of the app (so installed will pull in all of them, but Feature A will only pull in the DAOs and Entities relevant for Feature A). The benefit of this is having a single database allowing relationships to be more easily formed. However this is also a double edged sword as depending on how dense your relationships are you may need to pull in the whole database anyway even if the feature only uses one Entity. Another potential issue is data integrity, I'm not entirely certain how it will work having multiple databases across different versions of the app. A user moving from instant to installed may end up losing data because the underlying database is different.

Option 3 (Single Database):
In this scenario you have a single database and collect all your entities and DAOs into a single data layer that is shared between all modules. This obviously isn't as ideal in code separation and means that feature A is required to include code that's only used in feature B. But it would ensure the integrity of data and wouldn't restrict entity relationships in any way.

**Comment by Yoshi3003** [comment]
To anyone who still has this issue, including me at the moment, I have come across this Medium [article](https://medium.com/mindorks/writing-a-modular-project-on-android-304f3b09cb37) and would like to reference it here. Hope it helps a little.

**Comment by karntrehan** [comment]
Thanks for linking my blog. Yes, I contacted Yigit after opening this issue, and went ahead with multiple databases for each module. Have not run into any problems as of now.

**Comment by karntrehan** [comment]
Create a base-db module and put your entire database into it. Share that instance across all feature modules

**Comment by ianhanniballake** [comment]
This issue isn't related to these samples. Feel free to track [the feature request on the issue tracker](https://issuetracker.google.com/issues/67967869).

**Comment by marlonlom** [comment]
@karntrehan could you provide more info about declaring a module for just database ... or are you mentioning the data layer (local + remote entities and data sources) ??

**Comment by karntrehan** [comment]
We ended up creating a separate library module containing the database and models. This  was then implemented in all the individual modules.

**Comment by mhelmi** [comment]
> We ended up creating a separate library module containing the database and models. This was then implemented in all the individual modules.

@karntrehan Could you please tell us more about the issues that made you make one module containing database and entities and not using a separate database from each module?
