### ISSUE TITLE
Share ViewModel  only bewteen fragments ,if I  use addToBackStack and  findFragmentByTag("").viewModelStore,What will be the problem？

### ISSUE THREAD

**Issue by lishuang08** [android/architecture-components-samples#359]
FragmentA   set  tag  "main"
`supportFragmentManager.beginTransaction().replace(R.id.fragment_a, FragmentA(),"main").commit()`
has a ViewModel
` val viewmodel by lazy {
        ViewModelProvider(viewModelStore, ViewModelProvider.NewInstanceFactory()).get(MainViewModel::class.java)
    }`

then   replace to FragmentB  with addToBackStack, so FragmentA will not destory
In  FragmentB  , I use findFragmentByTag  get FragmentA's viewModelStore
` val viewmodel by lazy {
     ViewModelProvider(activity?.supportFragmentManager?.findFragmentByTag("main")?.viewModelStore
                ?: viewModelStore, ViewModelProvider.NewInstanceFactory()).get(MainViewModel::class.java)  }`

for this code, when destory FragmentA, the viewmodel will destory; if use 
`ViewModelProvider(activity, ViewModelProvider.NewInstanceFactory()).get(MainViewModel::class.java)`
the viewmodel will not destory

it works for me now , bug  i'm not sure it will has some problems 
will the FragmentA's viewmodelstore destory ,when it in backstack?   And it will has other problems?

**Comment by ianhanniballake** [comment]
Generally, we'd suggest you use [Navigation's back stack](https://developer.android.com/guide/navigation/navigation-programmatic#navbackstackentry) if you need to create a ViewModel associated with a particular entry on the back stack.

In the future (after [this feature request](https://issuetracker.google.com/issues/124181028) is finished), fragments on the back stack will be destroyed and you won't have direct access to them or their ViewModels. Since you're relying on those fragments to exist, I would not recommend building upon that assumption.
