### ISSUE TITLE
DiffUtil.ItemCallback no working in sample "PagingWithNetworkSample"

### ISSUE THREAD

**Issue by XiaoQiWen** [android/architecture-components-samples#364]
When I just get data from the web,DiffUtil is not triggered when loading more data.
LiveData<PagedList<Value>> trigger adapter.submitList(it) when acquiring data for the first time.
How should I use Paging correctly

Please forgive my bad English！

**Comment by XiaoQiWen** [comment]
anyone answer me?

**Comment by abhinav272** [comment]
@XiaoQiWen, I think this is the expected behavior.
The PagedList internally grows larger as new items are loaded and it has nothing to do with `onChanged()` in your view.

The `onChanged()` comes into play when you invalidate the `DataSource` and prepares a new set of `PagedList` and its producer(`DataSource`), then your view will receive a callback in `onChanged()` giving you the new object of `PagedList` which contains the updated pages of data.
