### ISSUE TITLE
how to update or add item in inMemory ItemKeyedDataSource paging library

### ISSUE THREAD

**Issue by hos3ein** [android/architecture-components-samples#376]
Hi
How to update or add item manually in list that provide with inMemory **ItemKeyedDataSource** paging library?
thanks

**Comment by nicusorflorin** [comment]
anything on this one? invalidating the data source is not a solution as it scrolls back to the top, and i wish to maintain the position where the user was in the list

**Comment by usmanrana07** [comment]
Having same issue. Is any workaround found so far?

**Comment by Sarquella** [comment]
**Note**: I'm assuming that in your custom _DataSource_ implementation, you are always just loading the first page items in its ```loadInitial``` method.

Although it seems that it scrolls back to the top, it actually does not, but instead removes all the non first page items.

The problem is that every time we invalidate the list, a new _DataSource_ instance is created, calling its ```loadInital``` method again. If it just loads the first page items, then, right after the invalidation, the list will **only** be composed by the **first** page items, until the ```loadAfter``` method is called again to load its corresponding items. So the problem is that, right after invalidation, we are telling the list that it only contains those first page items, so it removes all the others (making it look like it scrolled again to the first item).

The trick is to make ```loadInitial``` not just load the first page items, but all the "already loaded items", so that after invalidation, the "new initial list" looks like the one before the invalidation.

To do so, a simple solution would be to create a class to hold the pages already loaded:
```
class PageTracker {
    var currentPage = 0
}
```

Then, pass an instance of it to our custom _DataSource_ and update accordingly:

```
class MyDataSource(private val pageTracker: PageTracker) : PageKeyedDataSource<Int, MyItem>() {

    override fun loadInitial(params: LoadInitialParams<Int>, callback: LoadInitialCallback<Int, MyItem>) {
        val alreadyLoaded = (pageTracker.currentPage + 1) * params.requestedLoadSize
        val items = getItems(0, alreadyLoaded)
        callback.onResult(data, null, pageTracker.currentPage + 1)
    }

    override fun loadAfter(params: LoadParams<Int>, callback: LoadCallback<Int, MyItem>) {
        pageTracker.currentPage = params.key
        /...
    }
}
```

Finally, create the ```PageTracker``` instance and pass it to each new _DataSource_:

```
val dataSourceFactory = object : DataSource.Factory<Int, MyItem>() {
    var pageTracker = PageTracker()
    override fun create(): DataSource<Int, MyItem> {
        dataSource = CustomDataSource(pageTracker)
         return dataSource
    }
}
```

---

It is important to remember that if for any reason it is required to refresh the whole list again, we must update the ```PageTracker``` instance to ```currentPage = 0``` before invalidating the list.

**Comment by dlam** [comment]
FWIW, this behavior is mostly baked into Paging3 now, with `PagingSource` providing `PagingState` to `getRefreshKey()`, which is used to determine the next key to use in next generation's initial load. Thanks for jumping in with the detailed answer though :smiley:
