### ISSUE TITLE
[PagingWithNetworkSample] Scroll position is offset when loading completes

### ISSUE THREAD

**Issue by astr0-4** [android/architecture-components-samples#659]
This is an issue I've seen in my own project and so I checked out how it is done here and I'm seeing the same bug. When loading the data for the first time using the `DB + Network` option, the scroll bar is not at the top when loading finishes, but partway down the screen. How can we keep the scroll position stuck to the top while loading? With a large dataset this is more obvious and it's not a great experience.

See recording here: https://drive.google.com/open?id=1OwT87Gj5BeGz-ld_fIyQaIJvfz_49Tut

**Comment by efratos1** [comment]
The same problem here

**Comment by zack-barakat** [comment]
I'm encountering the same issue, I'm using only network data source.
Can you resolve this issue @yigit

**Comment by yaraki** [comment]
@dlam

**Comment by joezorry** [comment]
I've also encountered it, but also not sure if it's anything I've implemented incorrectly.
It seems when using placeholders this is happening.

**Comment by dlam** [comment]
So it seems the issue is that RecyclerView is using the loading spinner as an anchor during initial load since Paging gives it an initial empty list + spinner, while it's waiting for the initialLoad to complete, which then completes with initial page + spinner.

There's a workaround here #751 - thanks for reporting the issue!

Another way to fix this would be to actually send a AsyncDiffer update to remove the spinner before loading in the initial page or to prevent the differ from ever successfully comparing the spinner.

**Comment by astr0-4** [comment]
Thanks for the fix @dlam! It turns out the issue in my app was because the app's sort order was different than the sort order of the data from the network. Thanks to you and the guys at dev summit for helping me resolve this bug 🙌 🙌
