### ISSUE TITLE
Main activity instantiated multiple times

### ISSUE THREAD

**Issue by 7Fab** [android/architecture-components-samples#736]
Regarding the advanced navigation samples and the bottom navigation... The check for savedinstancestate == null is necessary? The main activity gets instantiated multiple times. If launchmode is set to single task or single instance, it doesn't work at all. How can I keep track of the state of the app with this?

**Comment by ianhanniballake** [comment]
Yes, the split in logic between `onCreate()` and `onRestoreInstanceState()` is indeed required since the bottom bar is the source of truth for the what the selected tab is and calling `setupBottomNavigationBar` when the saved state is not null in `onCreate()` would reset the selected tab (that's why `onRestoreInstanceState()` also calls it).
