### ISSUE TITLE
AutoValueCleared is not suitable for collection classes?

### ISSUE THREAD

**Issue by yihuajia** [android/architecture-components-samples#814]
Hello, I want to understand why AutoValueCleard is not suitable for collection classes, because it will report an error when using a collection class as a generic
eg:    private var list by autoCleared<MutableList<String>>()
         list.add("test")
throw an exception:should never call auto-cleared-value get when it might not be available

**Comment by ianhanniballake** [comment]
`by autoCleared` doesn't handle initializing your variable, you'll still need to say `list = mutableListOf()` at some point.

There's a bigger question on why you're using `by autoCleared()` for anything other than Views since the whole point of it is to clear out view references in `onDestroyView` for you; there'd be no reason to use it with a MutableList of Strings.
