### ISSUE TITLE
Advanced Navigation Sample: child fragment lifecycle is always destroyed if using viewLifecycleOwner 

### ISSUE THREAD

**Issue by CraZyLegenD** [android/architecture-components-samples#827]
Using the advanced navigation sample

The first fragment of the bottom navigation contains view pager2 adapter with a constructor the fragment itself (as I can see it sets the fragment manager to child fragment manager).
Now into the fragments from the view pager, I was observing a live data, but if I use

liveData.observe(viewLifecycleOwner....
the viewLifecycleOwner is CREATED upon first-time navigation, but when I go to other fragments from the bottom navigation and come back, the viewpager2 position is retained with no problems 

the viewLifecycleOwner is DESTROYED 

this issue is fixed if I use
liveData.observe(this) where this is the fragment itself

How this thing happens is 

MainActivity has the code of the advanced navigation sample where it sets the bottomNav using the extensions provided for multiple stack support.

BottomNavigation 1st destination let's call it FirstFragment

FirstFragment has a ViewPager2
and it's Pager Adapter looks like this

```
class FavoritesPagerAdapter(fragment: Fragment) : FragmentStateAdapter(fragment) {

    override fun getItemCount(): Int = 2

    override fun createFragment(position: Int): Fragment {
        return when (position) {
            0 -> {
                FragmentFavoriteStuff1()
            }
            1 -> {
                FragmentFavoriteStuff2()
            }
            else -> {
                throw IllegalArgumentException()
            }
        }
    }
}
```

Now inside FragmentFavoriteStuff1

I have a view model that exposes a list, live data list of items and I have

```
myViewModel.adapterList.observe(viewLifecycleOwner){
...
}
```
THIS code breaks because viewLifeCycleOwner is in state CREATED upon first time clicking on the fragment, if I navigate to another destination from the bottom navigation and come back to FragmentFavoriteStuff1

viewLifeCycleOwner is in state DESTROYED

The workaround is if I use 
```
myViewModel.adapterList.observe(this){
...
}
```
where this is the lifecycle of FragmentFavoriteStuff1

**Comment by CraZyLegenD** [comment]
@ianhanniballake

**Comment by ianhanniballake** [comment]
The `viewLifecycleOwner` is created directly before `onCreateView` and destroyed in `onDestroyView`. If you're seeing it be destroyed between those two methods (i.e., in `onViewCreated()`, etc.), then you should [file a bug against fragments](https://issuetracker.google.com/issues/new?component=460964) with a minimal sample that reproduces that issue.

It is intentional that your `FirstFragment` (and any fragments within it) get their views destroyed and recreated when you go to another tab via your bottom nav and come back. That's precisely why you need to use `viewLifecycleOwner` since otherwise your `FirstFragment` will have multiple observers running concurrently (one from the first `observe(this)`, then the second `observe(this)`) assuming you're calling `observe()` in `onCreateView()` or `onViewCreated()`.

Given that this isn't a problem with the samples here (that code works fine), but a problem with your code, you should probably ask a question on [StackOverflow](www.stackoverflow.com) with enough code to reproduce your issue.
